extends: airbnb
parserOptions:
  sourceType: script
rules:
  comma-dangle: 0
  func-names: 0
  no-console: 0
  no-new: 0
  no-param-reassign: 0
  object-curly-spacing: 0
  space-before-function-paren: 0
  strict: [2, 'global']
